// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzeriaApp.Models;

#nullable disable

namespace PizzeriaApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230610211029_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("IngredientPizza", b =>
                {
                    b.Property<int>("IngredientsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PizzasId")
                        .HasColumnType("INTEGER");

                    b.HasKey("IngredientsId", "PizzasId");

                    b.HasIndex("PizzasId");

                    b.ToTable("IngredientPizza");

                    b.HasData(
                        new
                        {
                            IngredientsId = 1,
                            PizzasId = 1
                        },
                        new
                        {
                            IngredientsId = 2,
                            PizzasId = 1
                        },
                        new
                        {
                            IngredientsId = 3,
                            PizzasId = 1
                        },
                        new
                        {
                            IngredientsId = 1,
                            PizzasId = 2
                        },
                        new
                        {
                            IngredientsId = 2,
                            PizzasId = 2
                        },
                        new
                        {
                            IngredientsId = 1,
                            PizzasId = 3
                        });
                });

            modelBuilder.Entity("PizzeriaApp.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tomato Sauce"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cheese"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ham"
                        });
                });

            modelBuilder.Entity("PizzeriaApp.Models.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Pizzas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Test0",
                            Price = 10.5f
                        },
                        new
                        {
                            Id = 2,
                            Name = "Test0",
                            Price = 12.5f
                        },
                        new
                        {
                            Id = 3,
                            Name = "Test0",
                            Price = 14.5f
                        });
                });

            modelBuilder.Entity("IngredientPizza", b =>
                {
                    b.HasOne("PizzeriaApp.Models.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PizzeriaApp.Models.Pizza", null)
                        .WithMany()
                        .HasForeignKey("PizzasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
